import "@/styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/components/header";
import Footer from "@/components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly <{ children: React.ReactNode; }> ) {
  return (
    <html lang="tr">
      <body className={`${inter.className} bg-BG1`}>
        <Header />
        <main>{children}</main>
        <Footer />
        </body>
    </html>
  );
}
