import "@/styles/globals.css";
import type { Metadata } from "next";
import Header from "@/components/site/header";
import Footer from "@/components/site/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <>
      <Header />
      <main className="w-full bg-BG1">{children}</main>
      <Footer />
    </>
  );
}
